- name: Gather Facts
  gather_facts: true
  hosts: all

  tasks:

#    - name: Host info
#      ansible.builtin.debug:
#        verbosity: 6
#        var: "hostvars"
#
#    - name: Full ansible_facts
#      ansible.builtin.debug:
#        verbosity: 5
#        var: "ansible_facts"

    ###
    # Collect data
    - name: get list of resource modules
      ansible.netcommon.network_resource:
      register: res_resources

    #- name: get hostname by resource module
    #  ansible.netcommon.network_resource:
    #    name: hostname
    #    state: gathered
    #  register: res_hostname

    - name: get hostname
      community.ciscosmb.ciscosmb_hostname:
        state: gathered
      register: ciscosmb_hostname
      when: ansible_network_os == 'community.ciscosmb.ciscosmb'

    - name: get facts
      community.ciscosmb.ciscosmb_facts:
        gather_subset: min
      register: ciscosmb_facts
      when: ansible_network_os == 'community.ciscosmb.ciscosmb'

    - name: get IOS hostname
      cisco.ios.ios_hostname:
        state: gathered
      register: ios_hostname
      when: ansible_network_os == 'cisco.ios.ios'

    - name: get IOS facts
      cisco.ios.ios_facts:
        gather_subset: min
      register: ios_facts
      when: ansible_network_os == 'cisco.ios.ios'

#    - name: Host NC facts
#      ansible.builtin.debug:
#        verbosity: 1
#        var: res_facts

#    - name: Selected ansible_facts
#      ansible.builtin.debug:
#        verbosity: 0
#        msg:
#          - "NC hostname:     {{ res_hostname | default('')}}"
#          - "Hostname:        {{ ansible_facts['net_hostname'] | default('') }}"
#          - "Model:           {{ ansible_facts['net_model'] | default('') }}"
#          - "Network OS:      {{ ansible_network_os | default('') }}"
#          - "Network OS (NC): {{ ansible_facts['net_system'] | default('') }}"
#          - "System:          {{ ansible_facts['system'] | default('') }}"
#          - "Machine:         {{ ansible_facts['architecture'] | default('') }}"
#          - "SN:              {{ ansible_facts['net_serialnum'] | default('') }}"
#          - "SN prod:         {{ ansible_facts['ansible_product_nam'] | default('') }}"
#          - "SW version:      {{ ansible_facts['net_version'] | default('') }}"
#          - "HW version:      {{ ansible_facts['net_hw_version'] | default('') }}"
#          - "config:          {{ ansible_facts['net_config'] | default('') }}"

    - name: Host facts 
      ansible.builtin.debug:
        verbosity: 6
        var: ansible_facts          
