- name: Gather Facts
  gather_facts: true
  hosts: all

  tasks:

    - name: Host info
      ansible.builtin.debug:
        verbosity: 6
        var: "hostvars"

    - name: Full ansible_facts
      ansible.builtin.debug:
        verbosity: 5
        var: "ansible_facts"

    ###
    # Collect data
    - name: get list of resource modules for given network_os
      ansible.netcommon.network_resource:
      register: res_resources

    - name: get CiscoSMB NC facts
      community.ciscosmb.ciscosmb_facts:
      register: res_facts
      when: ansible_network_os == 'community.ciscosmb.ciscosmb'
    
    - name: get CiscoIOS NC facts
      cisco.ios.ios_facts:
      register: res_facts
      when: ansible_network_os == 'cisco.ios.ios'

    - name: get CiscoSMB NC hostname
      community.ciscosmb.ciscosmb_hostname:
      register: res_hostname
      when: ansible_network_os == 'community.ciscosmb.ciscosmb'
    
    - name: get CiscoIOS NC hostname
      cisco.ios.ios_hostname:
      register: res_hostname
      when: ansible_network_os == 'cisco.ios.ios'

    - name: show results
      ansible.builtin.debug:
        verbosity: 1
        msg:
          - "NC resources: {{ res_resources }}"
          - "NC facts:     {{ res_facts }}"
          - "NC hostname:  {{ res_hostname }}"

    - name: Selected ansible_facts
      ansible.builtin.debug:
        verbosity: 1
        msg:
          - "Hostname:        {{ ansible_facts['net_hostname'] | default('') }}"
          - "Model:           {{ ansible_facts['net_model'] | default('') }}"
          - "Network OS:      {{ ansible_network_os | default('') }}"
          - "Network OS (NC): {{ ansible_facts['net_system'] | default('') }}"
          - "System:          {{ ansible_facts['system'] | default('') }}"
          - "Machine:         {{ ansible_facts['architecture'] | default('') }}"
          - "SN:              {{ ansible_facts['net_serialnum'] | default('') }}"
          - "SN prod:         {{ ansible_facts['ansible_product_nam'] | default('') }}"
          - "SW version:      {{ ansible_facts['net_version'] | default('') }}"
          - "HW version:      {{ ansible_facts['net_hw_version'] | default('') }}"
          - "config:          {{ ansible_facts['net_config'] | default('') }}"
          
